### ISSUE TITLE
Sorting folders?

### ISSUE THREAD

**Issue by moonheart08** [amoffat/supertag#11]
My personal programming projects folder is a _disaster_, and this seems just about perfect for sorting it. How could I do that?

**Comment by amoffat** [comment]
Tell me more about what you mean by sorting your folders

**Comment by moonheart08** [comment]
Each project I have is it's own folder, so I was wondering if I could use this tag system with entire folders and not just files.

**Comment by amoffat** [comment]
You can! Just follow the instructions in the docs for tagging a file, but do it with a folder instead.
