### ISSUE TITLE
Error when tagging a file with spaces in filename (NotFound)

### ISSUE THREAD

**Issue by TIAcode** [amoffat/supertag#16]
I just installed the latest release package of tag, and started tagging my files. However when encountering a file with spaces in the filename, I get the error:
Error: IO error: Os { code: 2, kind: NotFound, message: "No such file or directory" }

    $ tag ln SJ3.EXE oldies/sj3
    $ mv SJ3.EXE S\ J3.EXE
    $ tag ln S\ J3.EXE oldies/sj3
    Error: IO error: Os { code: 2, kind: NotFound, message: "No such file or directory" }

Same result if I enclose the filename in double quotes instead of quoting the space with \

**Comment by amoffat** [comment]
Thanks for reporting. The fix is out in v0.1.4. I didn't quote `$@` on its way through a bash script into the AppImage, so bash was splitting files with spaces.
