### ISSUE TITLE
Do not hardcode /mnt as base path for mounting.

### ISSUE THREAD

**Issue by raingloom** [amoffat/supertag#19]
Like the title says. A program should not presume that it knows where a user wants to mount something.

Also, please use something other than GitHub.

**Comment by raingloom** [comment]
Also, on Linux you should use `/run/user/$UID/gvfs` or something similar, instead of every user fighting over `/mnt`.

**Comment by amoffat** [comment]
`/mnt` and `/Volumes` are just defaults and can be overridden via [`mount.basedir`](https://amoffat.github.io/supertag/config.html#base-dir). You can mount it wherever you want.

**Comment by raingloom** [comment]
On Wed, 17 Mar 2021 17:00:22 -0700
Andrew Moffat ***@***.***> wrote:

> `/mnt` and `/Volumes` are just defaults and can be overridden via
> [`mount.basedir`](https://amoffat.github.io/supertag/config.html#base-dir).
> You can mount it wherever you want.
> 

The idea is that the mount command should let me specify the mount
point as an argument, just like how other FUSE file systems work. Or at
least the ones I can recall using. (archivemount, sshfs)
I can't really just put /run/user/$UID in the config file because my
user has a different UID on each machine and the config doesn't
evaluate environment valuables, and rightly so.
It's also entirely possible that I don't want to mount $collection at
$basepath/$collection, but some entirely unrelated path, like, idk,
/srv/http/tagfs, or whatever. Which is basically what I am actually
trying to do.

**Comment by raingloom** [comment]
Well, I patched it.

https://git.sr.ht/~raingloom/supertag/commit/9259d9557c0377e811f50a6779daa9d69479cbc4.patch
